name: undefined-solve-plugin
extra-source-files:
- package.yaml
ghc-options:
- -Wall
library:
    dependencies:
    - base >=4.7 && <5
    - deepseq >=1.3 && <1.5
    - ghc
    - ghc-tcplugins-extra
    - template-haskell
    - containers
    source-dirs: plugin
    exposed-modules:
    - Undefined.Solve.Plugin
tests:
    invoke:
        dependencies:
        - base
        - undefined-solve-plugin
        main: Main.hs
        source-dirs:
        - plugin-test
version: '1.0.0.0'
